#define M_FUSIONSTOR_START "1000, start"
#define M_FUSIONSTOR_EXIT_NORMAL "1001, exit normal"
#define M_FUSIONSTOR_EXIT_ERROR "1002, exit"
#define M_FUSIONSTOR_RESTART "1003, restart"
#define M_FUSIONSTOR_ASSERT_WARN "1004, assert"
#define M_FUSIONSTOR_PAXOS_WARN "1005, get master fail"
#define M_FUSIONSTOR_RECOVER_TOOLONG_WARN "1006, restart too long"
#define M_FUSIONSTOR_HB_TIMEOUT_WARN "1007, hb timeout"
#define M_FUSIONSTOR_FENCE_WARN "1008, fence fail"
//#define M_FUSIONSTOR_ACCEPT "1007, FusionStor accept"
//#define M_FUSIONSTOR_CLOSE_WARN "1008, FusionStor close"
//#define M_FUSIONSTOR_DATA_VERSION_ERROR "1003, FusionStor data version error"

//#define M_ROORTABLE_SYNC_ERROR "2000, root table, async worker exit"
//#define M_ROORTABLE_JNL_OPEN_ERROR "2001, root table, open jnl error"
//#define M_ROORTABLE_QUORUM_SYNC_ERROR "2002, root table, quorum sync error"
//#define M_ROORTABLE_CHECK_ADMIN_ERROR "2003, root table, check last decree fail"

#define M_DISK_OFFLINE_WARN "3000, disk offline"
//#define M_DISK_ONLINE "3001, disk online"
//#define M_DISK_DELETED "3002, disk was deleted"
//#define M_DISK_CTL_ERROR "3003, disk ctl error"
#define M_DISK_IO_ERROR "3004, disk i/o"
#define M_DISK_META_ERROR "3005, disk meta"
#define M_DISK_CACHED_ERROR "3006, disk cached "

//#define M_NET_SEND_ERROR "4000, net send error"
//#define M_NET_PREP_ERROR "4001, net prep error"
//#define M_NET_ENOENT "4002, net Machine is not on the network"
//#define M_NET_CRC_ERROR "4003, net crc error"
//#define M_NET_VIP_ERROR "4004, net vip error"
//#define M_NET_RPC_ERROR "4005, net rpc error"
//#define M_NET_SOCKET_ERROR "4006, net socket error"
//#define M_NET_SOCKET_UDP_ERROR "4007, net socket udp error"
//#define M_NET_SOCKET_UNIX_ERROR "4008, net socket unix error"
#define M_NET_VIP_SET "4010, net vip set"
#define M_NET_VIP_SET_ERROR "4011, net vip set error"
#define M_NET_VIP_UNSET "4020, net vip unset"

//#define M_DATA_VOLUME_CREATE "5000, volume create"
//#define M_DATA_VOLUME_UNLINK "5001, volume unlink"
//#define M_DATA_POOL_CREATE "5002, pool create"
//#define M_DATA_POOL_UNLINK "5003, pool unlink"
//#define M_DATA_VOLUME_CHANGE "5004, volume change"
//#define M_DATA_POOL_CHANAGE "5005, pool change"
//#define M_DATA_SCAN "5004, scan" //?如果不加warn，是不是没必要在 syslog 中体现。
#define M_DATA_RECOVER_WARN "5005, recover"
#define M_DATA_VOLUME_WARN "5006, volume" //create, unlink, load, truncate, rollback...etc. error
#define M_DATA_POOL_WARN "5007, pool"
#define M_DATA_CHUNK_WARN "5008, chunk"
#define M_DATA_TABLE_ERROR "5009, pool table"
#define M_DATA_CLEANUP_ERROR "5010, cleanup"

#define M_LICENSE_ERROR "6002, license"

//#define M_SYS_SETTIMER_WARN "8000, settimer error"
//#define M_SYS_LOCK_WARN "8001, lock error"
//#define M_SYS_LEASE_WARN "8002, lesase error"
//#define M_SYS_TASK_WARN "8003, task warn"
//#define M_SYS_TASK_NOT_FOUND_WARN "8004, task not found"
//#define M_SYS_TASK_REUSED_WARN "8005, task reused"
//#define M_SYS_TASK_INVALID_TIME_WARN "8006, task invalid time"
//#define M_SYS_BUFFER_CHECK_WARN "8007, buffer checke error"
//#define M_SYS_FONITFY_WARN "8008, fonitfy error"

#define M_PROTO_ISCSI_ERROR "9100, iscsi"
#define M_PROTO_ISCSI_LOGIN_ERROR "9101, login failed"
#define M_PROTO_NBD_ERROR "9200, nbd"
//#define M_PROTO_NFS_ERROR "9300, nfs error"
//#define M_PROTO_SHEEPDOG_ERROR "9400, sheepdog error"

//#define M_ISCSI_CHAP_ERROR "9000, chap error"
//#define M_ISCSI_LOGIN_ERROR "9000, login error"
//#define M_ISCSI_UNKNOW_AUTH "9000, unknow auth error"
//#define M_ISCSI_REP_ERROR "9000, unexpected response command"
//#define M_ISCSI_REP_ERROR "9000, unexpected response command"
